#!/usr/bin/env bash

fatal() {
    local exitcode="$1"; shift
    echo 1>&2 "$@"
    exit $exitcode
}

input_file="$1"; shift
output_dir="$1"; shift
[ -z "$output_dir" -o -n "$1" ] \
    && fatal 129 'Usage: krita-explode <input.kra> <output.kra.d>'
